### ISSUE TITLE
feat: Documentation framework

### ISSUE THREAD

**Issue by onerandomusername** [discord-modmail/modmail#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues and there is no existing issue.

### What is the feature?

Hosting documention.

Should be both current and to be implemented features.

@bast0006, I'm putting you in charge of getting the framework for this out there.

### Would you like to implement this yourself?

No, someone else can implement it

**Comment by Shivansh-007** [comment]
My suggestion is that we switch to using [MkDocs](https://www.mkdocs.org/) using the [MkDocs Material Theme](https://github.com/squidfunk/mkdocs-material) with GitHub Pages for hosting.

MkDocs Material theme provides several non-intrusive extensions for collapsible, tabs, and callouts that make the result documentation more readable, and a lot more. The FastAPI documentation is built on a few custom extensions, and you know how good documentation it is.

**Comment by onerandomusername** [comment]
Most of the documentation will be written on how to use the bot, not necessarily the code. 

The one part of the code that hopefully will be autogenerated is the plugin framework.

Because of preview environments, I'd like to use cloudflare pages for hosting.
